version: "3"

services:
  deliverit-back:
    build: .
    # env-file:
    #   - .env
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    # depends_on:
    #   - mongodb

  deliverit-front:
    image: facundoinza/deliverit-front:dd456a37d9fab4693d1cf064ee509ce028a72ff3

    ports:
      - "3001:3000"
# mongodb:
#   image: mongo:latest
#   volumes:
#     - mongodb_data:/data/db
#   ports:
#     - "27017:27017"

# volumes:
#   mongodb_data:
