# version: '3'

# services:
#   app:
#     build: .
#     command: npm start
#     volumes:
#       - .:/app
#     ports:
#       - "8080:8080"
#     environment:
#       - .env
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo:latest
#     volumes:
#       - mongodb_data:/data/db
#     ports:
#       - "27017:27017"

# volumes:
#   mongodb_data:
